[package]
name = "pasetors"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.1"
base64 = "0.12.3"
rand_core = "0.5.0"

[dev-dependencies]
hex = "*"

[dependencies.orion]
git = "https://github.com/brycx/orion"
branch = "master"
default-features = false